name: JIRA Auto-Link
 
on:
  workflow_dispatch:
 
jobs:
  disabled:
    runs-on: ubuntu-latest
 
    steps:
      - name: Jira Auto-Link Disabled
        run: echo "Jira auto-link workflow is disabled."